### ISSUE TITLE
CSS: Next your media queries inside your css elements

### ISSUE THREAD

**Issue by BaseInfinity** [solflare/solflare.github.io#5]
If you're applying multiple css rules to the same element depending on media queries, then it's best to target the element first, then next all the media queries inside there.

For example part of this CSS:
```
@media (max-width: 499px){
    .item
    {
        width: 90%;
    }
}
@media (min-width:500px) and (max-width:1000px){
    .item
    {
        width: 50%;
        margin: 2.5%;
    }
    #itemContainer div:nth-child(2n+1)
    {
        clear:left;
    }
}
@media (min-width: 1001px){
    .item
    {
        width: 27%;
        margin: 1.5%;
    }
    #itemContainer div:nth-child(3n+1)
    {
        clear:left;
    }
}

.item{
    float:left;
    text-align: center;
    border:1px solid #AAA;
    border-color:#299979;
    padding:.25em;
}
```

Could be rewritten as:
```

.item {
    float:left;
    text-align: center;
    border:1px solid #AAA;
    border-color:#299979;
    padding:.25em;

    @media (max-width: 499px ){
          width: 90%;
    }
    
    @media (min-width:500px) and (max-width:1000px) {
        width: 50%;
        margin: 2.5%;
    }
}

```

That way you don't have to repeat your selector ```.item``` and it keeps all your rules pertaining to one element together.

**Comment by solflare** [comment]
I tried several ways of implementing the media queries in this fashion but none worked properly like it is now. I couldn't figure out why it wouldn't work correctly so any insight would be greatly appreciated.

**Comment by BaseInfinity** [comment]
Sorry, nesting media queries only works with SASS or LESS, my bad. 

http://thesassway.com/intermediate/responsive-web-design-part-2

This is fine the way it is.
